#                                                           Developed by Ruben_Artz
#
#                                                     (MC.ARTZSTUDIO.DEV @ (C) 2018-2026)

name: 'ToastAPI'
version: '${version}'
main: 'artzstudios.dev.toast.Main'
authors: [
  'Ruben_Artz', 'Wuason6x9'
]
website: 'https://github.com/RubenArtz/SimpleToastApi'
folia-supported: true